[package]
name = "endringer"
version = "0.4.0"
edition = "2024"

description = "Lib for VCS change inspection."
authors = ["nabbisen <nabbisen@scqr.net>"]
license = "Apache-2.0"

categories = ["development-tools", "data-structures"]
keywords = ["git", "jj", "utility"]
repository = "https://github.com/nabbisen/endringer"
readme = "README.md"
rust-version = "1.85.0"

[profile.release]     # shrink executable size
opt-level = "z"
lto = true
# panic = "abort"
strip = true
codegen-units = 1

[profile.dev]         # to reasonably improve productivity
opt-level = 1         # slightly optimize
lto = false           # disable link-time optimizations
# strip = "debuginfo" # reduce size
incremental = true

[dependencies]
anyhow = "1"
gix = "0"
