[workspace]
members = [
    "crates/endringer-core",
    "crates/endringer-git",
    "crates/endringer-jj",
    "crates/endringer",
    "crates/endringer-async",
]
resolver = "2"

[workspace.package]
version      = "0.18.1"

edition      = "2024"
authors      = ["nabbisen"]
license      = "Apache-2.0"
repository   = "https://github.com/nabbisen/endringer"
rust-version = "1.85.0"

[workspace.dependencies]
endringer-core  = { path = "crates/endringer-core",  version = "0.18.1" }
endringer-git   = { path = "crates/endringer-git",   version = "0.18.1" }
endringer-jj    = { path = "crates/endringer-jj",    version = "0.18.1" }
endringer       = { path = "crates/endringer",       version = "0.18.1" }
anyhow          = "1"
gix             = { version = "0.77", features = ["blame", "attributes"] }
tokio           = { version = "1", features = ["rt", "rt-multi-thread"] }
tempfile        = "3"

[profile.release]
opt-level     = "z"
lto           = true
strip         = true
codegen-units = 1

[profile.dev]
opt-level   = 1
lto         = false
incremental = true
