[package]
name         = "endringer-git"
description  = "Git backend for endringer (powered by gix)."
readme       = "README.md"
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
endringer-core = { workspace = true }
anyhow         = { workspace = true }
gix            = { workspace = true }
